Fix for ctz and clz
CraneStation/lightbeam pull request #23
Opened 2019-05-14 20:20 UTC by afinch7

Closes #21

Ideally we should detect if a machine supports `tzcnt` and `lzcnt` correctly and use those instead when possible.

2019-05-15 07:01 UTC, eira-fransham requested changes
I'm impressed by how successfully you implemented a not-insignificant change on this project on your first try, the abstractions are pretty eclectic and easy to get wrong (I might switch to using some kind of `Rc`-like type that automatically refcounts to avoid the register-leaking problems that you have here). There's only one error that needs to be fixed, my other comments are just things that could be better but that aren't absolutely necessary.

2019-05-15 07:01 UTC, eira-fransham commented on .gitignore
> +.vscode
This should be in your user `.gitignore` and not in the lightbeam `.gitignore`

2019-05-15 07:01 UTC, eira-fransham commented on src/backend.rs
> +                    ((imm.as_int().unwrap() as i32).leading_zeros() as i32).into()
You can use `imm.as_i32` here, which will correctly fail if given the wrong type. Lightbeam expects a validated Wasm file but this acts as a safeguard.

2019-05-15 07:01 UTC, eira-fransham commented on src/backend.rs
> +                    ((imm.as_int().unwrap() as u64).leading_zeros() as u64).into()
As above, you can use `as_i64`

2019-05-15 07:01 UTC, eira-fransham commented on src/backend.rs
> +                let temp_2 = self.take_reg(I64).unwrap();
You need to free the unused temp register (`temp_2`) otherwise we'll leak registers. `self.free_value(ValueLocation::Reg(temp_2))` is the canonical way to do that, although it's kinda ugly. I'm trying to avoid reaching directly into `block_state` but you'll also see `self.block_state.regs.release(...)` too.

2019-05-15 12:11 UTC, afinch7 commented on .gitignore
> +.vscode
Didn't even know you could have a user `.gitignore`. 👍

2019-05-15 13:05 UTC, afinch7 commented
@Vurich Never worked on compilers much before, but I would say automatic resource allocation is the way to go here. I might give that one a try after I get this merged.

2019-05-20 10:24 UTC, Vurich commented
> @Vurich Never worked on compilers much before, but I would say automatic resource allocation is the way to go here. I might give that one a try after I get this merged.

Automatic resource allocation is good for sure, but it's much more complicated than it may seem at first glance because some instructions require allocating specific registers and others require it to be possible to allocate a register even if all have been allocated already (by pushing and popping). Manually allocating and freeing is a PITA but makes it a lot easier to deal with edge-cases since you only need to maintain invariants at function boundaries. Ideally we'd have a better framework to handle this, but it's a lot of work.

2019-05-22 10:14 UTC, eira-fransham approved these changes
Can you run rustfmt quickly? There are some empty lines and that should remove them and fix any other formatting issues at the same time. Otherwise this looks perfect. Thank you!

2019-05-22 10:14 UTC, Vurich commented on src/backend.rs
> +                if is_x86_feature_detected!("lzcnt") {
Thanks! This is fine for now but we want to use Cranelift's target system eventually (it's currently not usable outside Cranelift though)

2019-05-22 16:54 UTC, merged